In [6]:
import numpy as np
matriz_3x3 = np.arange(9).reshape(3,3)
print(matriz_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
matriz_identidad = np.identity(6)
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
