In [10]:
#PARTE 1
# Importa la biblioteca NumPy en tu entorno de programación

import numpy as np3

# Crea una matriz bidimensional llamada ventas_mensuales con una dimensión de 12 filas (representando los meses del año) 
# y 4 columnas (representando los productos vendidos). Los valores de la matriz representarán las ventas mensuales de cada producto.

ventas_mensuales = np.array([[300,260,450,600],[300,400,873,600],[567,932,450,126],\
                            [400,350,983,934],[765,400,450,600],[300,400,125,600],\
                            [670,632,450,600],[300,973,450,871],[890,763,450,643],\
                            [872,400,450,123],[987,400,982,600],[300,235,450,600]])

# Imprime la matriz ventas_mensuales para verificar su contenido.
print(ventas_mensuales)

[[300 260 450 600]
 [300 400 873 600]
 [567 932 450 126]
 [400 350 983 934]
 [765 400 450 600]
 [300 400 125 600]
 [670 632 450 600]
 [300 973 450 871]
 [890 763 450 643]
 [872 400 450 123]
 [987 400 982 600]
 [300 235 450 600]]


In [18]:
# PARTE 2

# Calcula el total_de_ventas_producto sumando los valores de cada columna utilizando la función sum() de NumPy.

# total de ventas por año
total_de_ventas_producto = np.sum(ventas_mensuales,axis=0)

# ventas totales de los 4 años
total_de_ventas_4años = np.sum(ventas_mensuales)

#Imprime el total_de_ventas_producto.
print(total_de_ventas_producto)
print(total_de_ventas_4años)

[6651 6145 6563 6897]
26256
